// <auto-generated />
using System;
using Flit.OT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.OT.Infrastructure.Migrations
{
    [DbContext(typeof(OtDbContext))]
    partial class OtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Identity.Infrastructure.Persistence.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.DocumentTypeCatalog", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("DefaultSortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("document_type_catalog", (string)null);
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.OtDocumentOrderItem", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcedureTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("DocumentTypeCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OtProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "ProcedureTypeCode", "DocumentTypeCode");

                    b.HasIndex("DocumentTypeCode");

                    b.HasIndex("OtProfileId");

                    b.HasIndex("ProcedureTypeCode");

                    b.HasIndex("TenantId", "ProcedureTypeCode", "Position");

                    b.ToTable("ot_document_order_items", (string)null);
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.OtProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DivipolCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntegrationMode")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DivipolCode")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ot_profiles", (string)null);
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.ProcedureDocumentDefault", b =>
                {
                    b.Property<string>("ProcedureTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("DocumentTypeCode")
                        .HasColumnType("text");

                    b.Property<int>("DefaultPosition")
                        .HasColumnType("integer");

                    b.HasKey("ProcedureTypeCode", "DocumentTypeCode");

                    b.HasIndex("DocumentTypeCode");

                    b.ToTable("procedure_document_defaults", (string)null);
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.ProcedureTypeCatalog", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("procedure_type_catalog", (string)null);
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.OtDocumentOrderItem", b =>
                {
                    b.HasOne("Flit.OT.Infrastructure.Persistence.Entities.DocumentTypeCatalog", "DocumentType")
                        .WithMany("DocumentOrderItems")
                        .HasForeignKey("DocumentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flit.OT.Infrastructure.Persistence.Entities.OtProfile", null)
                        .WithMany("DocumentOrderItems")
                        .HasForeignKey("OtProfileId");

                    b.HasOne("Flit.OT.Infrastructure.Persistence.Entities.ProcedureTypeCatalog", "ProcedureType")
                        .WithMany("DocumentOrderItems")
                        .HasForeignKey("ProcedureTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flit.Identity.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("ProcedureType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.OtProfile", b =>
                {
                    b.HasOne("Flit.Identity.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("Flit.OT.Infrastructure.Persistence.Entities.OtProfile", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.ProcedureDocumentDefault", b =>
                {
                    b.HasOne("Flit.OT.Infrastructure.Persistence.Entities.DocumentTypeCatalog", "DocumentType")
                        .WithMany("ProcedureDefaults")
                        .HasForeignKey("DocumentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Flit.OT.Infrastructure.Persistence.Entities.ProcedureTypeCatalog", "ProcedureType")
                        .WithMany("DocumentDefaults")
                        .HasForeignKey("ProcedureTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.DocumentTypeCatalog", b =>
                {
                    b.Navigation("DocumentOrderItems");

                    b.Navigation("ProcedureDefaults");
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.OtProfile", b =>
                {
                    b.Navigation("DocumentOrderItems");
                });

            modelBuilder.Entity("Flit.OT.Infrastructure.Persistence.Entities.ProcedureTypeCatalog", b =>
                {
                    b.Navigation("DocumentDefaults");

                    b.Navigation("DocumentOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
