// <auto-generated />
using System;
using Flit.Procedures.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Procedures.Infrastructure.Migrations
{
    [DbContext(typeof(ProceduresDbContext))]
    [Migration("20260612150154_AddProcedureInstances")]
    partial class AddProcedureInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("OtDivipolCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OtTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcedureTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleQueryValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureTypeId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("procedure_instances", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstanceActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalDataJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsLegalRepresentative")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("PersonKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentActorId");

                    b.HasIndex("ProcedureInstanceId", "SortOrder");

                    b.ToTable("procedure_instance_actors", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstanceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcedureInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureInstanceId", "Label")
                        .IsUnique();

                    b.ToTable("procedure_instance_documents", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleQueryMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("procedure_types", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureTypeId", "SortOrder");

                    b.ToTable("procedure_type_actors", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureTypeId", "SortOrder");

                    b.ToTable("procedure_type_documents", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstance", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", "ProcedureType")
                        .WithMany()
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstanceActor", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstanceActor", "ParentActor")
                        .WithMany()
                        .HasForeignKey("ParentActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("Actors")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentActor");

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstanceDocument", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstance", "ProcedureInstance")
                        .WithMany("Documents")
                        .HasForeignKey("ProcedureInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureInstance");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeActor", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", "ProcedureType")
                        .WithMany("Actors")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeDocument", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", "ProcedureType")
                        .WithMany("Documents")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureInstance", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
