// <auto-generated />
using System;
using Flit.Procedures.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Procedures.Infrastructure.Migrations
{
    [DbContext(typeof(ProceduresDbContext))]
    partial class ProceduresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleQueryMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("procedure_types", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureTypeId", "SortOrder");

                    b.ToTable("procedure_type_actors", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcedureTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureTypeId", "SortOrder");

                    b.ToTable("procedure_type_documents", (string)null);
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeActor", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", "ProcedureType")
                        .WithMany("Actors")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureTypeDocument", b =>
                {
                    b.HasOne("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", "ProcedureType")
                        .WithMany("Documents")
                        .HasForeignKey("ProcedureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcedureType");
                });

            modelBuilder.Entity("Flit.Procedures.Infrastructure.Persistence.Entities.ProcedureType", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
