// <auto-generated />
using System;
using Flit.Companies.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flit.Companies.Infrastructure.Migrations
{
    [DbContext(typeof(CompaniesDbContext))]
    [Migration("20260611145813_InitialCompaniesSchema")]
    partial class InitialCompaniesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LegalName");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyMatriculaConfig", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMiscProcedures")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowNewVehicleFiling")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId");

                    b.ToTable("company_matricula_config", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyNotificationConfig", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<string>("ClientApiSettings")
                        .HasColumnType("jsonb");

                    b.Property<int>("NotificationTarget")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId");

                    b.ToTable("company_notification_config", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyPaymentConfig", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowFlitGateway")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowOt")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowOther")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId");

                    b.ToTable("company_payment_config", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyRuntConfig", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailoverTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderCredentials")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SecondaryProvider")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId");

                    b.ToTable("company_runt_config", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanySignatureConfig", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("BuyerSignatureType")
                        .HasColumnType("integer");

                    b.Property<int>("SellerSignatureType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("VaultEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("VaultSettings")
                        .HasColumnType("jsonb");

                    b.HasKey("CompanyId");

                    b.ToTable("company_signature_config", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyTrafficAuthorityMatrix", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("CompanyId", "AuthorityCode");

                    b.HasIndex("AuthorityCode");

                    b.HasIndex("CompanyId", "IsEnabled");

                    b.ToTable("company_traffic_authority_matrix", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyTraspasoConfig", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OnlyOwnVehicles")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyId");

                    b.ToTable("company_traspaso_config", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.RuntProviderCatalog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("runt_provider_catalog", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.TenantUserException", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("tenant_user_exceptions", (string)null);
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.TrafficAuthority", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("traffic_authorities", (string)null);
                });

            modelBuilder.Entity("Flit.Identity.Infrastructure.Persistence.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Flit.Identity.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.Company", b =>
                {
                    b.HasOne("Flit.Identity.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.Company", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyMatriculaConfig", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithOne("MatriculaConfig")
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.CompanyMatriculaConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyNotificationConfig", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithOne("NotificationConfig")
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.CompanyNotificationConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyPaymentConfig", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithOne("PaymentConfig")
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.CompanyPaymentConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyRuntConfig", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithOne("RuntConfig")
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.CompanyRuntConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanySignatureConfig", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithOne("SignatureConfig")
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.CompanySignatureConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyTrafficAuthorityMatrix", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.TrafficAuthority", "Authority")
                        .WithMany("CompanyMatrix")
                        .HasForeignKey("AuthorityCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithMany("TrafficAuthorityMatrix")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.CompanyTraspasoConfig", b =>
                {
                    b.HasOne("Flit.Companies.Infrastructure.Persistence.Entities.Company", "Company")
                        .WithOne("TraspasoConfig")
                        .HasForeignKey("Flit.Companies.Infrastructure.Persistence.Entities.CompanyTraspasoConfig", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.TenantUserException", b =>
                {
                    b.HasOne("Flit.Identity.Infrastructure.Persistence.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flit.Identity.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.Company", b =>
                {
                    b.Navigation("MatriculaConfig");

                    b.Navigation("NotificationConfig");

                    b.Navigation("PaymentConfig");

                    b.Navigation("RuntConfig");

                    b.Navigation("SignatureConfig");

                    b.Navigation("TrafficAuthorityMatrix");

                    b.Navigation("TraspasoConfig");
                });

            modelBuilder.Entity("Flit.Companies.Infrastructure.Persistence.Entities.TrafficAuthority", b =>
                {
                    b.Navigation("CompanyMatrix");
                });
#pragma warning restore 612, 618
        }
    }
}
